# =====================
# RiskRadar Secrets
# =====================

# Financial data API 
finnhub_api_key = "d018oq9r01qile5u5a5g"
 
alphavantage_key = "330WKDI9AG4VQDN8" 

# Reddit API credentials (PRAW)
reddit_client_id = "EnYq-fFoagN5Yj3H5nnHDA"
reddit_client_secret = "D405xooZarLhpIgqCzpQ8T0Bu6hAVQ"
reddit_user_agent = "RiskRadarBot/0.1 by Hopeful_Ad4918"

# NewsAPI key
news_api_key = "e1c073eef47d4558bfd14c43f5bff337"

# Toggle for custom fine-tuned model (optional)
use_finetuned_model = false

#Bearer Token: AAAAAAAAAAAAAAAAAAAAAJ%2Fb0wEAAAAA1O25VQEbESNexQ6Sfty92YK19KQ%3D86osKOSsfy7QEWNBIkzOgEctYbrJnwLkGsdIpN1eppn1vfvq27
#Access Token: 1917686293758136320-IKluk8MMrngUAD8Uzif6eQDB8we42d
#Access Token Secret: VNEx4ElCrQMFmeLwrpw7Kg7RUVgsrZpIy3Xb56aEk18lg
