# =====================
# RiskRadar Secrets
# =====================

# Financial data API 
finnhub_api_key = "Your key  goes here"
 
alphavantage_key = "Your key  goes here" 

# Reddit API credentials (PRAW)
reddit_client_id = ""Your key  goes here"
reddit_client_secret = " "
reddit_user_agent = " "

# NewsAPI key
news_api_key = "Your key  goes here"

# Toggle for custom fine-tuned model (optional)
use_finetuned_model = false

